# Generated by Django 5.2 on 2025-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('seg_nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('apellido_m', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('rol', models.CharField()),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
