# Generated by Django 5.2 on 2025-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='tema',
        ),
        migrations.AddField(
            model_name='video',
            name='temas',
            field=models.ManyToManyField(related_name='videos', to='core.tema'),
        ),
    ]
