# Generated by Django 5.2 on 2025-05-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_funcionario',
            field=models.BooleanField(default=True, verbose_name='Es Funcionario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario')], max_length=20, verbose_name='Rol'),
        ),
    ]
