# Generated by Django 5.2 on 2025-06-04 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_encuesta_opcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tema"
                    ),
                ),
            ],
            options={
                "unique_together": {("tema", "fecha")},
            },
        ),
    ]
