# Generated by Django 5.2 on 2025-06-04 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='frase',
        ),
        migrations.AddField(
            model_name='tramite',
            name='frase_original',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='encuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites', to='core.encuesta'),
        ),
    ]
