# Generated by Django 5.2 on 2025-06-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_tramite_frase_tramite_frase_original_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contador", models.PositiveIntegerField(default=0)),
                ("fecha", models.DateField()),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes",
                        to="core.tema",
                    ),
                ),
            ],
        ),
    ]
