# Generated by Django 5.2 on 2025-06-10 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_informe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingVideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Palabra clave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Reporte de vídeo faltante',
                'verbose_name_plural': 'Reportes de vídeos faltantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
